apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml

configMapGenerator:
  - name: mockoon-config
    namespace: mockoon-ns
    files:
      - auth-server-oauth2.json
