spring:
  application:
    name: service
  threads:
    virtual:
      enabled: off
  cloud:
    vault:
      uri: http://localhost:8200
      token: root
      scheme: http
      kv:
        enabled: true
        default-context: ${spring.application.name}
  config:
    import:
      - "vault://"

server:
  port: 8081

management:
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
  endpoints:
    web:
      exposure:
        include: health, info
logging:
  level:
    org.springframework.vault: trace
