apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-server-deployment
  namespace: discovery-server-ns
  labels:
    app: discovery-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discovery-server
  template:
    metadata:
      labels:
        app: discovery-server

    spec:
      containers:
        - name: discovery-server
          image: hashicorp/consul:1.22.3
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8500
              name: http
              protocol: TCP
          envFrom:
            - configMapRef:
                name: discovery-server-config
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "300m"
          livenessProbe:
            tcpSocket:
              port: 8500
            initialDelaySeconds: 45
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            tcpSocket:
              port: 8500
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          securityContext:
            allowPrivilegeEscalation: false
          volumeMounts:
            - name: tmp-volume
              mountPath: /tmp
      volumes:
        - name: tmp-volume
          emptyDir: {}
