apiVersion: v1
kind: ConfigMap
metadata:
  name: authorization-server-config
  namespace: authorization-server-ns
data:
  SPRING_PROFILES_ACTIVE: "k8s"
  OTEL_SERVICE_NAME: gateway
  OTEL_EXPORTER_OTLP_ENDPOINT: http://opentelemetry-collector.monitoring.svc.cluster.local:4318
  OTEL_EXPORTER_OTLP_PROTOCOL: http/protobuf
  OTEL_TRACES_EXPORTER: otlp
  OTEL_METRICS_EXPORTER: otlp
  OTEL_LOGS_EXPORTER: otlp
  OTEL_INSTRUMENTATION_MICROMETER_ENABLED: "true"
  OTEL_INSTRUMENTATION_LOGBACK_MDC_ENABLED: "true"
  OTEL_INSTRUMENTATION_LOGBACK_APPENDER_ENABLED: "true"

