apiVersion: v1
kind: ConfigMap
metadata:
  name: authorization-server-config
  namespace: authorization-server-ns
data:
  SPRING_PROFILES_ACTIVE: "k8s"
#  SPRING_APPLICATION_JSON: >-
#    {
#      "spring": {
#        "security": {
#          "oauth2": {
#            "authorizationserver": {
#              "client": {
#                "oidc-client": {
#                  "registration": {
#                    "redirect-uris": ["https://local.ks.tv/login/oauth2/code/oidc-client"],
#                    "post-logout-redirect-uris": ["https://local.ks.tv/"]
#                  }
#                },
#                "gateway": {
#                  "registration": {
#                    "redirect-uris": ["https://local.ks.tv/login/oauth2/code/gateway"],
#                    "post-logout-redirect-uris": ["https://local.ks.tv/"]
#                  }
#                }
#              }
#            }
#          }
#        }
#      }
#    }
#  SPRING_LIQUIBASE_CHANGE_LOG: "classpath:/db.changelog/master.xml"

