apiVersion: v1
kind: ConfigMap
metadata:
  name: authorization-server-config
  namespace: authorization-server-ns
data:
  SERVER_PORT: "9000"
  SPRING_PROFILES_ACTIVE: "k8s"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres-db-postgresql:5432/auth_server"
  SPRING_DATASOURCE_USERNAME: "postgres"
  SPRING_DATASOURCE_PASSWORD: "postgres"
  SPRING_DATASOURCE_DRIVER: "org.postgresql.Driver"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "validate"
  SERVER_FORWARD_HEADERS_STRATEGY: "native"
  SERVER_SERVLET_CONTEXT_PATH: "/authorization"
  SPRING_LIQUIBASE_CHANGE_LOG: "classpath:/db.changelog/master.xml"
  LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY: "info"
  LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SESSION_JDBC: "info"
