apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: authorization-server-ingress
  namespace: authorization-server-ns
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - local.ks.tv
      secretName: local.ks.tv

  rules:
    - host: local.ks.tv
      http:
        paths:
          - path: /authorization
            pathType: Prefix
            backend:
              service:
                name: authorization-server
                port:
                  name: http