apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: authorization-server-ingress
  namespace: authorization-server-ns
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: authorization-server.local
      http:
        paths:
              - path: /
                pathType: Prefix
                backend:
                  service:
                    name: authorization-server
                    port:
                      name: http