apiVersion: v1
kind: Secret
metadata:
  name: authorization-server-secret
  namespace: authorization-server-ns
type: Opaque
stringData:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/auth_server"
  SPRING_DATASOURCE_USERNAME: "postgres"
  SPRING_DATASOURCE_PASSWORD: "postgres"
  SPRING_SECURITY_OAUTH2_AUTHORIZATION_SERVER_CLIENT_OIDC-CLIENT_SECRET: "secret"
  SPRING_SECURITY_OAUTH2_AUTHORIZATION_SERVER_CLIENT_GATEWAY_SECRET: "gateway-secret"
  SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_ID: ""
  SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_SECRET: ""
  SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KIP_CLIENT_ID: "kstv-test"
  SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KIP_CLIENT_SECRET: "OjN5BZ8Ykw2dotppZPZTh2IowrcdOz3MiLh7AuOe"
