apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  accounts.rpaliuha: login
  accounts.mdemydovych: login
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-rbac-cm
    app.kubernetes.io/part-of: argocd
data:
  policy.csv: |
    g, rpaliuha, role:admin
    g, mdemydovych, role:admin
---
apiVersion: v1
kind: Secret
metadata:
  name: argocd-secret
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-secret
    app.kubernetes.io/part-of: argocd
type: Opaque
data:
  accounts.rpaliuha.password: JDJhJDEwJHhZQ213RGhlY0hZaDNEUVlGeHR6QU9pTDlZTklmN20vcjVldFNoOFZUSldtYkY0b2llQm5p
  accounts.rpaliuha.passwordMtime: MjAyNi0wNi0wM1QxMDo0Nzo1MVo=
  accounts.mdemydovych.password: JDJhJDEwJDlUT01ZelJFTzRmN3ptYU9DWXBQdC43MEs0YnEyakM3RDN1S3NwcTh2a0pHeC5xMlVVRTlX
  accounts.mdemydovych.passwordMtime: MjAyNi0wNi0wM1QxMDo0Nzo1MVo=
