apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-catalog-config
  namespace: demo-catalog-ns
data:
  SERVER_PORT: "8083"
  SPRING_PROFILES_ACTIVE: "k8s"
  LOGGING_LEVEL_ROOT: "trace"
  OTEL_SERVICE_NAME: catalog
  OTEL_EXPORTER_OTLP_ENDPOINT: http://opentelemetry-collector.monitoring.svc.cluster.local:4318
  OTEL_EXPORTER_OTLP_PROTOCOL: http/protobuf
  OTEL_TRACES_EXPORTER: otlp
  OTEL_METRICS_EXPORTER: otlp
  OTEL_LOGS_EXPORTER: otlp
  OTEL_INSTRUMENTATION_MICROMETER_ENABLED: "true"
  OTEL_INSTRUMENTATION_LOGBACK_MDC_ENABLED: "true"
  OTEL_INSTRUMENTATION_LOGBACK_APPENDER_ENABLED: "true"