apiVersion: v1
kind: Service
metadata:
  name: demo-catalog
  namespace: demo-catalog-ns
  labels:
    app: demo-catalog
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8083
      name: http
    - port: 9876
      targetPort: 9876
      name: debug
    - port: 9875
      targetPort: 9875
      name: jmx
  selector:
    app: demo-catalog
