apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-gateway-ingress
  namespace: ingress-gateway-ns
  annotations:
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://local.ui.ks.tv"
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET, POST, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-headers: "DNT,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - local.api.ks.tv
      secretName: local.api.ks.tv
  rules:
    - host: local.api.ks.tv
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ingress-gateway
                port:
                  name: http

