apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis-cache
  namespace: argocd
spec:
  project: default
  source:
    chart: redis
    repoURL: registry-1.docker.io/bitnamicharts
    targetRevision: 18.x.x
    helm:
      values: |
        image:
          tag: latest
        architecture: standalone
        auth:
          enabled: true
          password: "YourSecurePassword"
        master:
          persistence:
            enabled: true
            size: 5Gi
        metrics:
          enabled: true
          image:
            registry: registry-1.docker.io
            repository: bitnami/redis-exporter
            tag: latest
          serviceMonitor:
            enabled: true
            labels:
              release: kube-prometheus-stack
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-gateway-ns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
