apiVersion: v1
kind: Secret
metadata:
  name: ingress-gateway-secret
  namespace: ingress-gateway-ns
type: Opaque
stringData:
  SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GATEWAY_CLIENT_SECRET: "gateway-secret"
  SPRING_DATA_REDIS_PASSWORD: "YourSecurePassword"
  SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GATEWAY_REDIRECT_URI: "http://localhost:8080/login/oauth2/code/gateway"
  SPRING_CLOUD_GATEWAY_SERVER_WEBFLUX_GLOBALCORS_CORS_CONFIGURATIONS: "http://localhost:8081,http://127.0.0.1:8081"
