spring:
  cloud:
    consul:
      host: discovery-server.discovery-server-ns.svc.cluster.local
      port: 8500
      discovery:
        prefer-ip-address: true
        instance-id: ${POD_NAME}
        deregister: true
        heartbeat:
          enabled: true
          reregister-service-on-failure: true
        enabled: true
        register: true
        fail-fast: false
      service-registry:
          auto-registration:
           enabled: true
  application:
    name: catalog

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTHORIZATION_SERVER_ISSUER_URI:https://auth.dev.k8s.plustvs.net/authorization}
          jwk-set-uri: http://authorization-server.authorization-server-ns.svc.cluster.local/authorization/oauth2/jwks
server:
  port: 8083
logging:
  level:
    web: trace

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  tracing:
    export:
      otlp:
        enabled: true
    sampling:
      probability: 1.0
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT:http://localhost:4318}/v1/traces
    logging:
      export:
        otlp:
          endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT:http://localhost:4318}/v1/logs
  logging:
    export:
      otlp:
        enabled: true
  otlp:
    metrics:
      export:
        enabled: true
        url: ${OTEL_EXPORTER_OTLP_ENDPOINT:http://localhost:4318}/v1/metrics
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
    tags:
      application: ${spring.application.name}
      instance-id: ${POD_NAME}
  observations:
    enable:
      all: true
