spring:
  application:
    name: catalog

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://auth.local.ks.tv/authorization
          jwk-set-uri: http://authorization-server.authorization-server-ns.svc.cluster.local/authorization/oauth2/jwks
server:
  port: 8083
logging:
  level:
    web: trace

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
